// AUTO-GENERATED by generate.sh — do not edit by hand.
const ALBUMS = [
  {
    name: "Sandan Valley",
    theme: "trekking",
    images: [
      "Images/Sandan Valley/IMG_2134.JPG",
      "Images/Sandan Valley/IMG_2143.jpg",
      "Images/Sandan Valley/IMG_2190.jpg",
      "Images/Sandan Valley/IMG_2214.jpg",
      "Images/Sandan Valley/IMG_2216.jpg",
      "Images/Sandan Valley/PXL_20260314_085816951.jpg",
      "Images/Sandan Valley/PXL_20260314_130519731.jpg",
      "Images/Sandan Valley/PXL_20260314_174034576.jpg",
      "Images/Sandan Valley/PXL_20260314_174052289.jpg",
      "Images/Sandan Valley/PXL_20260314_174055606.jpg",
      "Images/Sandan Valley/PXL_20260314_174057931.jpg",
      "Images/Sandan Valley/PXL_20260315_042619397.jpg",
      "Images/Sandan Valley/PXL_20260315_043505198.jpg",
      "Images/Sandan Valley/IMG_2028.jpeg",
      "Images/Sandan Valley/IMG_2030.jpeg",
      "Images/Sandan Valley/IMG_2085.jpeg",
      "Images/Sandan Valley/IMG_2107.jpeg",
      "Images/Sandan Valley/IMG_2129.jpeg",
    ],
    audio: null
  },
];
