#!/bin/bash
# Regenerates data.js by scanning the Images folder.
# Run this whenever you add/remove folders or images.

cd "$(dirname "$0")"
IMAGES_DIR="./Images"
OUTPUT="./data.js"

# Theme map by folder name (case-insensitive keywords). Add more here later.
get_theme() {
  local name_lower
  name_lower=$(echo "$1" | tr '[:upper:]' '[:lower:]')
  case "$name_lower" in
    *trek*|*camp*|*hike*|*mountain*|*valley*|*sandan*) echo "trekking" ;;
    *beach*|*sea*|*ocean*) echo "beach" ;;
    *city*|*urban*) echo "city" ;;
    *) echo "trekking" ;;  # default while only trekking theme is built
  esac
}

{
  echo "// AUTO-GENERATED by generate.sh — do not edit by hand."
  echo "const ALBUMS = ["
  for folder in "$IMAGES_DIR"/*/; do
    [ -d "$folder" ] || continue
    folder_name=$(basename "$folder")
    theme=$(get_theme "$folder_name")
    echo "  {"
    echo "    name: \"$folder_name\","
    echo "    theme: \"$theme\","
    echo "    images: ["
    # Collect images
    shopt -s nullglob nocaseglob
    for img in "$folder"*.jpg "$folder"*.jpeg "$folder"*.png "$folder"*.gif "$folder"*.webp; do
      img_name=$(basename "$img")
      # Skip hidden/system files
      [[ "$img_name" == .* ]] && continue
      echo "      \"Images/$folder_name/$img_name\","
    done
    echo "    ],"
    # Find first audio file (if any)
    audio_path="null"
    for aud in "$folder"*.mp3 "$folder"*.wav "$folder"*.m4a "$folder"*.ogg; do
      aud_name=$(basename "$aud")
      [[ "$aud_name" == .* ]] && continue
      audio_path="\"Images/$folder_name/$aud_name\""
      break
    done
    shopt -u nullglob nocaseglob
    echo "    audio: $audio_path"
    echo "  },"
  done
  echo "];"
} > "$OUTPUT"

echo "Wrote $OUTPUT"
